apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-sleep
  name: busybox-sleep
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox-sleep
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
