apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox1
    resources: {}
    args: ['/bin/sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: vol
      mountPath: /etc/foo
  - image: busybox
    name: busybox2
    resources: {}
    args: ['/bin/sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: vol
      mountPath: /etc/foo
  volumes:
  - name: vol
    emptyDir: {}
  
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
